### ISSUE TITLE
Update pypi release

### ISSUE THREAD

**Issue by FredHappyface** [addisonElliott/pypdn#13]
Would it be possible to update the pypi release as the last update was in April

Thank you :)

**Comment by addisonElliott** [comment]
Yes I can. Sometime this week I'll try to get to it. Hold me accountable if I don't.

**Comment by addisonElliott** [comment]
Alright, just released. Give that a test and let me know if it's all working as expected.

**Comment by FredHappyface** [comment]
Works great in my testing (py3.8 + py3.9) thank you very much!
