### ISSUE TITLE
Not working on python 3.8

### ISSUE THREAD

**Issue by samedii** [addisonElliott/pypdn#2]
Still working on python 3.7 though.

**Comment by addisonElliott** [comment]
Hello,

Ran tests on Python 3.8.2 on Windows x64 and they completed successfully. Do you have a testcase that fails or some more information to go on?

PRs are welcome by the way.

**Comment by samedii** [comment]
Okay sorry then I probably did something wrong. I downgraded to 3.7 and it suddenly worked but it must be something else. Closing this

**Comment by addisonElliott** [comment]
It's no problem. If you figure out what you did, then I would be open to fixing it, or documenting what went wrong so the next person doesn't have the problem as well. Thanks!
