### ISSUE TITLE
Question: Minimal Dependency Versions

### ISSUE THREAD

**Issue by FredHappyface** [addisonElliott/pypdn#5]
Looking at your requirements.txt I see that version numbers have been omitted 

This kind of relates to my pull request and the use of python 2. My thoughts are that if the dependencies do not have a compatible python 2 version then there would be no need to support this.

For example the most recent version of the Pillow version requires python 3.5+ (I know this project does not use that library)

The closest to a solution I have managed to come up with my own project is a Frankenstein combination of poetry and dephell (to keep requirements and setup.py)  - though there is no way I've found to work out the minimum version of a library I can use aside from manual testing

Would you consider adding the minimum versions of each dependency to your requirements.txt?

Thanks again for your time :grinning:

**Comment by addisonElliott** [comment]
Yeah, I didn't put version numbers. At the time of designing this library, I didn't know what the minimum versions were for these libraries, so I just left them blank.

If you have an idea of what the minimum versions should be, I'd be happy to accept a PR.

**Comment by FredHappyface** [comment]
I'd be happy to take a look at it though I suspect it'll take some trial and error - an probably a VM or two 😊

**Comment by FredHappyface** [comment]
I've taken a look and have found the following:


datetime.timezone was added in Python 3.2. So it is normal to get an import error in e.g. Python 2.7.


In that case there would be no need to support python 2. An alternative may exist though I suspect that this might be going out of your way to support it as this time. 


Looks like https://teamtreehouse.com/community/datetimetimezone-python-27-attribute-error
has some info on this

As a side question, would it be possible for you to update the pypi version when you get the chance?

**Comment by addisonElliott** [comment]
Sure, I was waiting to do that once we finished this up. So it sounds like Python 2 is not supported then due to that?

That's fine, we can just drop Python 2 support.

**Comment by FredHappyface** [comment]
Ah cheers (me jumping the gun there 😄) 

Ok. Would you be happy for me to create a pull request for that?

**Comment by addisonElliott** [comment]
That would be great. What's the PR, to remove any Python 2 related stuff?

If so, can you add a note in the README that this project is for Python 3+ only?

**Comment by FredHappyface** [comment]
Yeah sure. I had a quick look on pypistats.org and the lowest version of python that it recons that this project is used on is python 3.5 🤔 (not sure how accurate that is tbh) 

Yeah I'll start that now. I'll keep trying to work out the minimum version of dependencies if this would be useful (unfortunately it is mostly trail and error)

**Comment by FredHappyface** [comment]
Finally worked out the minimum python version. I was originally going to use poetry but it didn't really work. The minimum version is 3.4 required by numpy 1.12 which is the lowest that has the flip function that you use

I'm going to push that commit and then open a pull request 

3.4
https://github.com/numpy/numpy/blob/maintenance/1.12.x/setup.py
3.3
https://bitbucket.org/stoneleaf/aenum/src/1.0/setup.py
2.5
https://github.com/scikit-image/scikit-image/blob/v0.10.x/setup.py
