### ISSUE TITLE
PRR: Replace Skimage with custom functions

### ISSUE THREAD

**Issue by FredHappyface** [addisonElliott/pypdn#8]
I have recently replaced Skimage with a few of my own functions in one of my libraries so I could make it work on python 3.5 (the most recent version requires python 3.6+). When looking at this further and then attempting to install pypdn for python 3.5+ I ran into the following trouble:

Installing matplotlib (3.0.3) caused trouble in a windows environment. This falls under Skimage. I was surprised to see the crazy amount of dependencies it required when I was only using about two functions:

```none
pypdn 1.0.5 Python package to read and write Paint.NET (PDN) images.
|-- aenum >=1.0
|-- numpy >=1.12
`-- scikit-image >=0.10
    |-- imageio >=2.3.0
    |   |-- numpy *
    |   `-- pillow *
    |-- matplotlib >=2.0.0,<3.0.0 || >3.0.0
    |   |-- cycler >=0.10
    |   |   `-- six * 
    |   |-- kiwisolver >=1.0.1
    |   |-- numpy >=1.11 (circular dependency aborted here)
    |   |-- pyparsing >=2.0.1,<2.0.4 || >2.0.4,<2.1.2 || >2.1.2,<2.1.6 || >2.1.6
    |   `-- python-dateutil >=2.1
    |       `-- six >=1.5 (circular dependency aborted here)
    |-- networkx >=2.0 
    |   `-- decorator >=4.3.0
    |-- pillow >=4.3.0 (circular dependency aborted here)
    |-- pywavelets >=0.4.0
    |   `-- numpy >=1.13.3 (circular dependency aborted here)
    `-- scipy >=0.19.0
        `-- numpy >=1.13.3 (circular dependency aborted here)
```

The question is would you accept a pull request that would replace these functions to reduce the number of dependencies required? (Pull Request Request - or PRR)

Thanks 😄

**Comment by addisonElliott** [comment]
Sure, I'd accept a PR if the skimage logic was relatively easy to implement in this library.

I don't have many calls to skimage functions.

**Comment by FredHappyface** [comment]
That's great, I'll make a start

**Comment by addisonElliott** [comment]
@FredHappyface I appreciate the help for this library. Sorry for the delay on merging the branch.

Would you like me to release a new version for this? Personally, I would prefer until more improvements are made but if you need it, then I can make an exception.

**Comment by FredHappyface** [comment]
@addisonElliott No worries at all! There's no rush. Would be great if you can but don't worry if you would prefer to bundle more stuff :smile: 

Glad I could be of help
